/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aerolineas;

import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author facu
 */
public class Busqueda extends JFrame {

    /**
     * Creates new form Busqueda
     * @param bv1
     */

    public Busqueda(BusquedaVuelos bv1){
        initComponents();
        jLabelAca.setText(bv1.getTxt1());
        jLabelAlla.setText(bv1.getTxt2());
        jLabelDias.setText(Integer.toString(bv1.getResu1()));
        LabelAÑ.setText(Integer.toString(bv1.getResu2()));
        LabelÑ.setText(Integer.toString(bv1.getResu3()));
        CalcularTripulantes();
        
    }

    private Busqueda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void CalcularTripulantes(){
        String grandes = LabelAÑ.getText();
        int grandesint = Integer.parseInt(grandes);
        grandesint = grandesint *1500;
        String niños = LabelÑ.getText();
        int niñosint = Integer.parseInt(niños);
        niñosint = niñosint * 1000;
        String suma = Integer.toString(grandesint + niñosint);
        System.out.println(suma);
        this.LabelÑinoA.setText(suma);
}

    public JLabel getLabelÑinoA() {
        return LabelÑinoA;
    }

    public void setLabelÑinoA(JLabel LabelÑinoA) {
        this.LabelÑinoA = LabelÑinoA;
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAca = new javax.swing.JLabel();
        jLabelAlla = new javax.swing.JLabel();
        jLabelDias = new javax.swing.JLabel();
        jLabelAyÑ = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelPFinal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelAlla1 = new javax.swing.JLabel();
        LabelAÑ = new javax.swing.JLabel();
        LabelÑ = new javax.swing.JLabel();
        LabelÑinoA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabelAca);
        jLabelAca.setBounds(12, 95, 80, 26);
        getContentPane().add(jLabelAlla);
        jLabelAlla.setBounds(117, 95, 94, 31);
        getContentPane().add(jLabelDias);
        jLabelDias.setBounds(290, 70, 80, 40);
        getContentPane().add(jLabelAyÑ);
        jLabelAyÑ.setBounds(380, 95, 0, 0);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(567, 12, 0, 0);

        jLabelPFinal.setText("Precio final");
        getContentPane().add(jLabelPFinal);
        jLabelPFinal.setBounds(30, 130, 77, 17);

        jLabel1.setText("Origen");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 48, 17);

        jLabel2.setText("Dias de viaje");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 50, 83, 17);

        jLabel3.setText("Destino");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 50, 54, 17);

        jLabel4.setText("Precio de tripulantes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 40, 163, 33);
        getContentPane().add(jLabelAlla1);
        jLabelAlla1.setBounds(223, 95, 94, 31);
        getContentPane().add(LabelAÑ);
        LabelAÑ.setBounds(748, 126, 0, 0);
        getContentPane().add(LabelÑ);
        LabelÑ.setBounds(693, 166, 0, 0);

        LabelÑinoA.setText("aca");
        getContentPane().add(LabelÑinoA);
        LabelÑinoA.setBounds(390, 70, 124, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAÑ;
    private javax.swing.JLabel LabelÑ;
    private javax.swing.JLabel LabelÑinoA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAca;
    private javax.swing.JLabel jLabelAlla;
    private javax.swing.JLabel jLabelAlla1;
    private javax.swing.JLabel jLabelAyÑ;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelPFinal;
    // End of variables declaration//GEN-END:variables
}
