/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aerolineas;

import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author salvagibert
 */
public class Compra extends javax.swing.JFrame {
    private String codigo=creaPass();
    private String texto1;
    private String texto2;
    private String texto3;
    private String texto4;
    private String texto5;
    private String texto6;
    private String texto7;
    private String texto8;
    
    /**
     * Creates new form Compra
     */
    public Compra(InfoVuelos v2) {
        initComponents();
        String text=area.getText();
        texto1=v2.getText1();
        area.setText(text+v2.getText1());
        text = area.getText();
        area.setText(text+"\n"+v2.getText2());
        text = area.getText();
        texto2=v2.getText2();
        area.setText(text+"\n"+v2.getText3());
        text = area.getText();
        texto3=v2.getText3();
        area.setText(text+"\n"+v2.getText4());
        text = area.getText();
        texto4=v2.getText4();
        area.setText(text+"\n"+v2.getText5());
        text = area.getText();
        texto5=v2.getText5();
        area.setText(text+"\n"+v2.getText6());
        texto6=v2.getText6();
        text = area.getText();
        area.setText(text+"\n"+v2.getText7());
        texto7=v2.getText7();
        text = area.getText();
        area.setText(text+"\n"+v2.getText8());
        texto8=v2.getText8();
        text = area.getText();
        area.setText(text+"\n"+"Codigo: "+codigo);
    }
    
    

   public String creaPass(){
        char[] elementos={'0','1','2','3','4','5','6','7','8','9' ,'a','b','c','d','e','f','g','h','i','j','k','l','m','n','ñ','o','p','q','r','s','t','u','v','w','x','y','z'};

        char[] conjunto = new char[8];
        String pass;
        
        for(int i=0;i<8;i++){
        int el = (int)(Math.random()*37);
        conjunto[i] = (char)elementos[el];
            }
        return pass = new String(conjunto);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtruta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        area.setEditable(false);
        area.setColumns(20);
        area.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtruta)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int opcion = dlg.showSaveDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION){
            File f = dlg.getSelectedFile();
            txtruta.setText(f.toString());
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ruta = txtruta.getText();
        String contenido = area.getText();
        
        try {
            FileOutputStream archivo = new FileOutputStream(ruta+".pdf");
            Document doc = new Document(PageSize.A7, 50, 50, 50, 50);
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            
            doc.close();
            
            JOptionPane.showMessageDialog(null, "Pdf correctamente creado ");
            
        } catch (Exception e) {
            System.out.println("Error");
        }
        FileWriter fichero = null;
        PrintWriter pw = null;
        try{
            fichero = new FileWriter("./src/aerolineas/registro.txt",true);
            pw = new PrintWriter(fichero);
            pw.println(texto1+";"+texto2+";"+texto3+";"+texto4+";"+texto5+";"+texto6+";"+texto7+";"+texto8+";"+codigo);
            
            
        } catch (Exception e) {
            e.printStackTrace();
            
        }finally {
            try{ 
                if (null != fichero)
                    fichero.close();}
                catch (Exception e2){
                        e2.printStackTrace();
                        }
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
